language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - cd atom-mail
  - npm run lint
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $repo_token
  local_dir: build
  on:
    branch:
      - master
      - devel
